site_name: OpenAI Python library documentation · UNOFFICIAL
site_author: Marsh Macy
site_description: Unofficial documentation for OpenAI's Python library
site_url: https://mmacy.github.io/openai-python/
repo_name: openai-python
repo_url: https://github.com/mmacy/openai-python/tree/docs
watch: [README.md, src/openai]

theme:
  name: material
  icon:
    repo: fontawesome/brands/github

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    #text: Sora # BIG!
    text: Inter
    #text: Actor

    code: Chivo Mono
    #code: Martian Mono # BIG!

  features:
    - content.code.annotate
    - header.autohide
    - search.share
    - search.suggest
    - toc.follow

    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          load_external_modules: true # 'true' picks up __all__ from __init__.py files
          import:
            - https://docs.python.org/3/objects.inv
            - https://docs.pydantic.dev/2.4/objects.inv
            #- https://www.python-httpx.org/ # NO OBJECTS.INV AVAILABLE
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: spacy
            docstring_style: google
            extensions:
              - griffe_inherited_docstrings
            filters: ["!^_"]
            heading_level: 3
            inherited_members: false
            merge_init_into_class: true
            separate_signature: true
            show_bases: true
            show_if_no_docstring: true
            show_root_full_path: false
            show_root_heading: true
            show_signature_annotations: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            unwrap_annotated: true

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/mmacy

nav:
  - index.md
  - get_started.md
  - API reference:
    - openai.md
    - pagination.md
    - version.md
    - openai.resources:
      - resources/index.md
      - openai.resources.audio: resources/audio/__init__.md
      - openai.resources.beta:
        - resources/beta/index.md
        - openai.resources.beta.assistants: resources/beta/assistants/__init__.md
        - openai.resources.beta.threads:
          - resources/beta/threads/index.md
          - openai.resources.beta.threads.messages: resources/beta/threads/messages/__init__.md
          - openai.resources.beta.threads.runs: resources/beta/threads/runs/__init__.md
      - openai.resources.chat: resources/chat/__init__.md
      - openai.resources.fine_tuning: resources/fine_tuning/__init__.md
    - openai.types:
      - types/index.md # was __init__.md
      - openai.types.audio: types/audio/__init__.md
      - openai.types.beta:
        - types/beta/index.md
        - openai.types.beta.assistants: types/beta/assistants/__init__.md
        - openai.types.beta.chat: types/beta/chat/__init__.md
        - openai.types.beta.threads:
          - types/beta/threads/index.md
          - openai.types.beta.threads.messages: types/beta/threads/messages/__init__.md
          - openai.types.beta.threads.runs: types/beta/threads/runs/__init__.md
      - openai.types.chat: types/chat/__init__.md
      - openai.types.fine_tuning: types/fine_tuning/__init__.md
      - openai.types.shared: types/shared/__init__.md
      - openai.types.shared_params: types/shared_params/__init__.md
