site_name: OpenAI Python library documentation (UNOFFICIAL)

site_author: Marsh Macy
site_description: Unofficial documentation for OpenAI's Python library
site_url: https://mmacy.github.io/openai-python/
repo_name: openai-python
repo_url: https://github.com/openai/openai-python
watch:
  - "docs/"
  - "examples/"
  - "src/"
  - "."

theme:
  name: material
  icon:
    repo: fontawesome/brands/github

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Actor
    code: Chivo Mono
    #text: Sora # BIG!
    #code: Martian Mono # BIG!

  features:
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

    - toc.follow

    - search.suggest
    - search.share

    - header.autohide

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          import:
            - https://docs.python.org/3/objects.inv
            - https://docs.pydantic.dev/2.4/objects.inv
            #- https://www.python-httpx.org/ # NO OBJECTS.INV AVAILABLE
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: table
            filters: ["!^_"]
            heading_level: 2
            inherited_members: false
            merge_init_into_class: true
            separate_signature: true
            show_bases: false
            show_if_no_docstring: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            unwrap_annotated: true

nav:
  - index.md
  - get_started.md
  - Modules:
    - openai:
      - openai.md
      - pagination.md
      - version.md
    - openai.resources: resources/__init__.md
    - openai.resources.audio: resources/audio/__init__.md
    - openai.resources.beta: resources/beta/__init__.md
    - openai.resources.beta.assistants: resources/beta/assistants/__init__.md
    - openai.resources.beta.threads: resources/beta/threads/__init__.md
    - openai.resources.beta.threads.messages: resources/beta/threads/messages/__init__.md
    - openai.resources.beta.threads.runs: resources/beta/threads/runs/__init__.md
    - openai.resources.chat: resources/chat/__init__.md
    - openai.resources.fine_tuning: resources/fine_tuning/__init__.md
    - openai.types:
      - types/index.md # was __init__.md
      - types/completion_choice.md
      - types/completion_create_params.md
      - types/completion_usage.md
      - types/completion.md
      - types/create_embedding_response.md
      - types/embedding_create_params.md
      - types/embedding.md
      - types/file_content.md
      - types/file_create_params.md
      - types/file_deleted.md
      - types/file_list_params.md
      - types/file_object.md
      - types/image_create_variation_params.md
      - types/image_edit_params.md
      - types/image_generate_params.md
      - types/image.md
      - types/images_response.md
      - types/model_deleted.md
      - types/model.md
      - types/moderation_create_params.md
      - types/moderation_create_response.md
      - types/moderation.md
    - openai.types.audio: types/audio/__init__.md
    - openai.types.beta: types/beta/__init__.md
    - openai.types.beta.assistants: types/beta/assistants/__init__.md
    - openai.types.beta.chat: types/beta/chat/__init__.md
    - openai.types.beta.threads: types/beta/threads/__init__.md
    - openai.types.beta.threads.messages: types/beta/threads/messages/__init__.md
    - openai.types.beta.threads.runs: types/beta/threads/runs/__init__.md
    - openai.types.chat: types/chat/__init__.md
    - openai.types.fine_tuning: types/fine_tuning/__init__.md
    - openai.types.shared: types/shared/__init__.md
    - openai.types.shared_params: types/shared_params/__init__.md