site_name: OpenAI Python library documentation · UNOFFICIAL
site_author: Marsh Macy
site_description: Unofficial documentation for OpenAI's Python library
site_url: https://mmacy.github.io/openai-python/
repo_name: openai-python
repo_url: https://github.com/mmacy/openai-python/tree/docs
watch: [README.md, src/openai]

theme:
  name: material
  icon:
    repo: fontawesome/brands/github

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    #text: Sora # BIG!
    text: Inter
    #text: Actor

    code: Chivo Mono
    #code: Martian Mono # BIG!

  features:
    - content.code.annotate
    - header.autohide
    - search.share
    - search.suggest
    - toc.follow

    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  # - gen-files:
  #     scripts:
  #     - scripts/gen_ref_nav.py # Can't run automatically because the src/openai/lib/azure.py busts the build
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          load_external_modules: true # 'true' picks up __all__ from __init__.py files
          import:
            - https://docs.python.org/3/objects.inv
            - https://docs.pydantic.dev/2.4/objects.inv
            #- https://www.python-httpx.org/ # NO OBJECTS.INV AVAILABLE
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: spacy
            docstring_style: google
            extensions:
              - griffe_inherited_docstrings
            filters: ["!^_"]
            heading_level: 3
            inherited_members: false
            merge_init_into_class: true
            separate_signature: true
            show_bases: true
            show_if_no_docstring: true
            show_root_full_path: false
            show_root_heading: false
            show_signature_annotations: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            unwrap_annotated: true

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/mmacy

nav:
  - Welcome:
    - index.md
    - Get started: get_started.md
    - API reference: reference/index.md
  - Get started: get_started.md
  - API reference: reference/
